// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwikdbxruhbjetbqhulp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aWtkYnhydWhiamV0YnFodWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTgyMzIsImV4cCI6MjA3NzQ3NDIzMn0._a6PlptQWscSJOIqtmZ8veDJAD89kwx3KSifh0NpC3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});